#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x
set -e

cd ${0%/*} || exit 1    # run from this directory
wmake libso library
wmake communicatorLR
wmake splitRansFoam
wmake splitLesFoam

# ----------------------------------------------------------------- end-of-file
