#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x
set -e

cd ${0%/*} || exit 1    # run from this directory
wclean library
wclean libso library
wclean communicatorLR
wclean splitRansFoam
wclean splitLesFoam

# ----------------------------------------------------------------- end-of-file
