#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso mutableIncoTurbulenceModels/muTurbulenceModel
wmake libso mutableIncoTurbulenceModels/muRAS
./mutableIncoTurbulenceModels/installMu
wmake 
wmake libso libFlexFieldAverage

# ----------------------------------------------------------------- end-of-file
